"""create-table

Revision ID: 92081a7df540
Revises: 8e7d93f8d026
Create Date: 2025-12-07 21:35:04.551031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92081a7df540'
down_revision: Union[str, Sequence[str], None] = '8e7d93f8d026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upload_jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_jobs', type_='foreignkey')
    op.drop_column('upload_jobs', 'user_id')
    # ### end Alembic commands ###
